//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaTec.SisPol.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TModelo
    {
        public int nmod_codigo { get; set; }
        public string cmod_descripcion { get; set; }
        public Nullable<int> nmar_codigo { get; set; }
        public string cmar_descripcion { get; set; }
        public int nmod_estdato { get; set; }
        public int nmod_estreg { get; set; }
        public string caud_usrcre { get; set; }
        public string caud_usract { get; set; }
        public Nullable<System.DateTime> daud_feccre { get; set; }
        public Nullable<System.DateTime> daud_fecact { get; set; }
        public Nullable<int> nmod_orden { get; set; }
    }
}
