//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaTec.SisPol.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMotorizado
    {
        public int nmot_codigo { get; set; }
        public Nullable<int> nper_codigo { get; set; }
        public Nullable<int> nsup_codigo { get; set; }
        public string cmot_dni { get; set; }
        public string cmot_nombres { get; set; }
        public string cmot_apepat { get; set; }
        public string cmot_apemat { get; set; }
        public string cmot_nombrecompleto { get; set; }
        public string cmot_celular { get; set; }
        public string cmot_telefono { get; set; }
        public string cmot_email { get; set; }
        public string cmot_sexo { get; set; }
        public Nullable<System.DateTime> dmot_fecasigna { get; set; }
        public string cmot_placamoto { get; set; }
        public Nullable<int> nmot_estdato { get; set; }
        public Nullable<int> nmot_estreg { get; set; }
        public string caud_usrcre { get; set; }
        public Nullable<System.DateTime> daud_feccre { get; set; }
        public string caud_usract { get; set; }
        public Nullable<System.DateTime> daud_fecact { get; set; }
    }
}
