//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaTec.SisPol.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TParamDetalle
    {
        public int npad_codigo { get; set; }
        public int npar_codigo { get; set; }
        public string cpad_descripcion { get; set; }
        public string cpad_valor { get; set; }
        public int npad_estreg { get; set; }
        public string caud_usrcre { get; set; }
        public Nullable<System.DateTime> daud_feccre { get; set; }
        public string caud_usract { get; set; }
        public Nullable<System.DateTime> daud_fecact { get; set; }
        public Nullable<int> npad_orden { get; set; }
    
        public virtual TParametrica TParametrica { get; set; }
    }
}
