//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaTec.SisPol.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPersonal
    {
        public int nper_codigo { get; set; }
        public string cper_dni { get; set; }
        public string cper_nombres { get; set; }
        public string cper_apepat { get; set; }
        public string cper_apemat { get; set; }
        public string cper_nombrecompleto { get; set; }
        public string cper_celular { get; set; }
        public string cper_telefono { get; set; }
        public string cper_email { get; set; }
        public string cper_sexo { get; set; }
        public Nullable<System.DateTime> dper_fecingreso { get; set; }
        public Nullable<int> nper_estdato { get; set; }
        public Nullable<int> nper_estreg { get; set; }
        public string caud_usrcre { get; set; }
        public Nullable<System.DateTime> daud_feccre { get; set; }
        public string caud_usract { get; set; }
        public Nullable<System.DateTime> daud_fecact { get; set; }
    }
}
