//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaTec.SisPol.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPuntoVenta
    {
        public int nptv_codigo { get; set; }
        public string caud_usrcre { get; set; }
        public Nullable<System.DateTime> daud_feccre { get; set; }
        public string caud_usract { get; set; }
        public Nullable<System.DateTime> daud_fecact { get; set; }
        public Nullable<int> nptv_estreg { get; set; }
        public string cubi_codigo { get; set; }
        public string cptv_direccion { get; set; }
        public string cptv_referencia { get; set; }
        public string ccon_telefono { get; set; }
        public Nullable<int> ncon_codcontacto { get; set; }
        public string ccon_celular { get; set; }
        public string ccon_nrodni { get; set; }
        public string ccon_nombres { get; set; }
        public string ccon_apepat { get; set; }
        public string ccon_apemat { get; set; }
        public string ccon_email { get; set; }
        public string cptv_RUC { get; set; }
        public Nullable<System.DateTime> dptv_fecalta { get; set; }
        public Nullable<System.DateTime> dptv_fecbaja { get; set; }
        public string cptv_nombre { get; set; }
        public Nullable<int> nptv_estdato { get; set; }
    }
}
