//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaTec.SisPol.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUsuario
    {
        public int nusr_codigo { get; set; }
        public string cusr_dni { get; set; }
        public string cusr_nombres { get; set; }
        public string cusr_apepat { get; set; }
        public string cusr_apemat { get; set; }
        public string cusr_email { get; set; }
        public string cusr_clave { get; set; }
        public int nusr_estdato { get; set; }
        public int nusr_estdreg { get; set; }
        public string caud_usrcre { get; set; }
        public string caud_usract { get; set; }
        public System.DateTime daud_feccre { get; set; }
        public Nullable<System.DateTime> daud_fecact { get; set; }
    }
}
